# Generated by Django 5.1.2 on 2024-11-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_options_alter_author_author_name_and_more'),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='author',
        ),
        migrations.AddField(
            model_name='publisher',
            name='author',
            field=models.ManyToManyField(related_name='publisher', to='author.author'),
        ),
    ]
