# Generated by Django 5.1.2 on 2024-11-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_remove_publisher_author_publisher_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='author',
            new_name='authors',
        ),
    ]
