# Generated by Django 5.1.2 on 2024-11-26 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_options_alter_author_author_name_and_more'),
        ('book', '0001_initial'),
        ('publisher', '0003_rename_author_publisher_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fk_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='author.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fk_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='publisher.publisher'),
        ),
    ]
